In [2]:
l1 = [2,3,4,5,6]
l1+[4]

[2, 3, 4, 5, 6, 4]

In [3]:
import numpy as np

In [4]:
a1 = np.array([2,3,4,5,6])

In [5]:
a1+4

array([ 6,  7,  8,  9, 10])

In [ ]:
What is NumPy?
It is a powerful python library used for
* Numerical Computations
* Working with arrays and matrices
* Mathematical operations
* Data Science and Machine Learning

NumPy:

Advanages of numpy
* Faster than python lists
* Uses less memory
* Supports multi-dimentional arrays 
* Large collections of mathematical functions

list vs array:
1 list we cannot do element wise operation but in array we can do.
2 array to list conversion is possible and also list to array conversion also possible but it will loss the dimnesion.
3 list is hetirogenious datatype but numpy is a homogenous datatype.

In [1]:
import numpy as np

In [12]:
a1 = np.array([45,89,12,30])

In [13]:
a1

array([45, 89, 12, 30])

In [14]:
a1.shape

(4,)

In [18]:
a2 = np.array([[10,20],[30,40]])
a2

array([[10, 20],
       [30, 40]])

In [19]:
a2.shape

(2, 2)

In [20]:
a2.ndim

2

In [21]:
a2.size

4

In [22]:
len(a2)

2

In [23]:
type(a2)

numpy.ndarray

In [24]:
a2.dtype

dtype('int64')

In [30]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.ones((2,3),dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [36]:
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [48]:
arr1 = np.arange(1,10,1)

In [49]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.reshape(arr1,(3,3),order='F')

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
# Create even number array from 1 to 20
arr2 = np.arange(2,21,2)

In [52]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
create 4x5 random numbers array

In [53]:
arr3 = np.random.rand(4,5).round(2)

In [54]:
arr3

array([[0.57, 0.01, 0.98, 0.94, 0.28],
       [0.16, 0.78, 0.55, 0.04, 0.69],
       [0.08, 0.4 , 0.87, 0.59, 0.29],
       [0.91, 0.41, 0.8 , 0.72, 0.16]])

In [55]:
arr4 = np.random.randint(1,100,(4,5))

In [56]:
arr4

array([[23, 55, 26, 82, 48],
       [64, 86, 37, 64,  4],
       [14, 40, 96, 11, 11],
       [28, 61, 59,  1, 87]], dtype=int32)

In [57]:
arr4.max()

np.int32(96)

In [4]:
# 1) Create a numpy array of {3X4} with numbers from 10 to 50
import numpy as np
arr = np.random.randint(10,50,12)
arr

array([41, 26, 31, 24, 41, 34, 32, 45, 42, 39, 39, 47], dtype=int32)

In [5]:
arr = arr.reshape(3,4)
arr

array([[41, 26, 31, 24],
       [41, 34, 32, 45],
       [42, 39, 39, 47]], dtype=int32)

In [7]:
# OR
arr = np.random.randint(10,50,(3,4))
arr

array([[12, 29, 41, 41],
       [12, 21, 38, 10],
       [39, 12, 38, 28]], dtype=int32)

In [8]:
np.linspace(10,50,12)

array([10.        , 13.63636364, 17.27272727, 20.90909091, 24.54545455,
       28.18181818, 31.81818182, 35.45454545, 39.09090909, 42.72727273,
       46.36363636, 50.        ])

In [9]:
np.linspace(10,50,12).round(2)

array([10.  , 13.64, 17.27, 20.91, 24.55, 28.18, 31.82, 35.45, 39.09,
       42.73, 46.36, 50.  ])

In [10]:
arr

array([[12, 29, 41, 41],
       [12, 21, 38, 10],
       [39, 12, 38, 28]], dtype=int32)

In [11]:
# to give row wise maximum value
np.max(arr,axis=1)

array([41, 38, 39], dtype=int32)

In [ ]:
row=1, column=0 in numpy
row=2, column=1 in pandas

In [14]:
np.max(arr,axis=1)

array([41, 38, 39], dtype=int32)

In [15]:
# if i want position not value
arr[1,2]

np.int32(38)

In [16]:
# from matrix only the first row
arr[0]

array([12, 29, 41, 41], dtype=int32)

In [18]:
arr[:,0]

array([12, 12, 39], dtype=int32)

In [20]:
arr[:2,:2]

array([[12, 29],
       [12, 21]], dtype=int32)

In [22]:
# even index row and odd index column elements
arr[::2,::2]

array([[12, 41],
       [39, 38]], dtype=int32)

In [23]:
arr.transpose()

array([[12, 12, 39],
       [29, 21, 12],
       [41, 38, 38],
       [41, 10, 28]], dtype=int32)

In [24]:
# To reverse the matrix
arr[::-1,::-1]

array([[28, 38, 12, 39],
       [10, 38, 21, 12],
       [41, 41, 29, 12]], dtype=int32)

In [31]:
# To normalisation, all the value should be in the range of 0 to 1;
# x-min/max-min
new = (arr - arr.min())/(arr.max()-arr.min())
new

array([[0.06451613, 0.61290323, 1.        , 1.        ],
       [0.06451613, 0.35483871, 0.90322581, 0.        ],
       [0.93548387, 0.06451613, 0.90322581, 0.58064516]])

In [32]:
new.round(2)

array([[0.06, 0.61, 1.  , 1.  ],
       [0.06, 0.35, 0.9 , 0.  ],
       [0.94, 0.06, 0.9 , 0.58]])

In [33]:
arr.max()

np.int32(41)

In [34]:
arr.min()

np.int32(10)

In [35]:
# Elements greater than 30 
arr[arr>30]

array([41, 41, 38, 39, 38], dtype=int32)

In [37]:
arr1 = np.array([1,2,3,4,5,-6,-7,-8])
arr1

array([ 1,  2,  3,  4,  5, -6, -7, -8])

In [41]:
# to replace all negative values by 0
arr1[arr1<0]=0
arr1

array([1, 2, 3, 4, 5, 0, 0, 0])